site_name: MarsGamme
site_description: Documentação de demonstração do projeto MarsGamme

nav:
  - Início: index.md
  - Arquitetura: architecture.md
  - Execução: running.md
  - Debugging: debugging.md

plugins:
  - techdocs-core
