apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: meu-servico
  description: Serviço de exemplo para demonstrar o Backstage
  annotations:
    github.com/project-slug: TEU_UTILIZADOR/MarsGamme
    backstage.io/techdocs-ref: dir:.
  tags:
    - nodejs
    - prototipo
  links:
    - url: https://github.com/TEU_UTILIZADOR/MarsGamme
      title: Repositório GitHub
      icon: github
spec:
  type: service
  lifecycle: experimental
  owner: user:default/guest
